register_new_building:
    path: /buildings
    controller: App\Building\Infrastructure\Controller\BuildingController::registerNew
    methods: [POST]

check_in:
    path: /buildings/{buildingId}/check-in
    controller: App\Building\Infrastructure\Controller\BuildingController::checkIn
    methods: [POST]

check_out:
    path: /buildings/{buildingId}/check-out
    controller: App\Building\Infrastructure\Controller\BuildingController::checkOut
    methods: [POST]

get_users_checked_in:
    path: /buildings/{buildingId}/users
    controller: App\Building\Infrastructure\Controller\BuildingController::getUsersCheckedIn
    methods: [GET]
